### ISSUE TITLE
scalastyle ImportOrderChecker rule seems vendor-specific

### ISSUE THREAD

**Issue by vicaba** [CodelyTV/scala_bootstrap#2]
I think that the `parameter`s of the ImportOrderChecker rule should be vendor agnostinc for a bootstrapping template. https://github.com/CodelyTV/scala_bootstrap/blob/0eef0ff61c5160aec0c59fde3a354351be221831/scalastyle-config.xml#L220 (`<parameter name="group.letgo">com\.letgo\..*</parameter>`) is not vendor agnostic.

**Comment by JavierCane** [comment]
Good one!

Fixed in commit https://github.com/CodelyTV/scala_bootstrap/commit/5f52607d2862ad05ced0c534b91a3928e2cfccc7 :) thx!
