### ISSUE TITLE
Deprecate it

### ISSUE THREAD

**Issue by rgomezcasas** [CodelyTV/scala_bootstrap#4]
We should deprecate it in favour of https://github.com/CodelyTV/scala-bootstrap-template.g8

**Comment by JavierCane** [comment]
Agree!

We could redirect to it from the ReadMe.md 🙂

**Comment by JavierCane** [comment]
[Done](https://github.com/CodelyTV/scala-basic-skeleton/commit/fe9a152ba6cc4b7b8473714cd386d67505b9341c) (It took a while 😅)
